# Generated by Django 3.2 on 2022-04-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220425_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(default='%Y-%m-%d %H:%M:%S'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_time',
            field=models.DateTimeField(default='%Y-%m-%d %H:%M:%S'),
        ),
    ]
