# Generated by Django 3.2 on 2022-04-28 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220425_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
