# Generated by Django 3.2 on 2022-04-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220428_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
    ]
