# Generated by Django 3.2 on 2022-04-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(null=True, verbose_name='个性签名'),
        ),
    ]
